name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake animations
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: biancaiolanda
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%235D4635&color_dots=%23F8F5EF,%23F0E6D9,%23DFC9AD,%23C5A381,%23967457
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23DFC9AD&color_dots=%23201812,%235D4635,%23967457,%23C5A381,%23F0E6D9

      - name: Publish animations
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
